Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Study_JPA
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none # none : 테이블을 드랍하지 않음
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hiernate.type: trace
